services:
  eql-demo:
    image: eql-demo:jazzy-py3.12
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    ports: 
      - 8888:8888
    # privileged: true
    user: root
    working_dir: /home/jovyan/work
    command: jupyter lab --allow-root --NotebookApp.token='' --no-browser --ip=0.0.0.0
    entrypoint: ["/home/jovyan/work/entrypoint.sh"]
    volumes:
      - ./:/home/jovyan/work
